### PR TITLE
Fix/persistence

### PR DESCRIPTION
**Pull request by rolfberkenbosch**
**Description of the change**
 I'm trying to fix the following issue:

'''
Unable to save changes: application spec is invalid: InvalidSpecError: Unable to generate manifests in charts/wikijs: rpc error: code = Unknown desc = failed to unmarshal manifest: error unmarshaling JSON: while decoding JSON: Object 'Kind' is missing in '{"---kind":"PersistentVolumeClaim","apiV
'''

Because the common is in this repo i cannot test it :( I have no clue how I can test this branch locally.

**Checklist** 
- [x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).

### CODE REVIEW

**Comment by bjw-s** [comment]
I don't think this change does what you think it does. This would break situations where there are multiple PVC's being created. Currently not at my laptop but I'll try to take a look at it later.

**Comment by rolfberkenbosch** [comment]
> I don't think this change does what you think it does. This would break situations where there are multiple PVC's being created. Currently not at my laptop but I'll try to take a look at it later.

Thanks!

**Comment by bjw-s** [comment]
I assume that you do not see this error with the default `values.yaml`? Could you perhaps share the values that trigger this issue for you?

**Comment by rolfberkenbosch** [comment]
> I assume that you do not see this error with the default `values.yaml`? Could you perhaps share the values that trigger this issue for you?

Hi I'm using the following options for wikijs:

      - name: persistence.data.storageClass
        value: "nfs-client"
      - name: persistence.data.enabled
        value: "true"
      - name: persistence.config.enabled
        value: "true"
      - name: persistence.config.storageClass
        value: "nfs-client"

**Comment by bjw-s** [comment]
> > I assume that you do not see this error with the default `values.yaml`? Could you perhaps share the values that trigger this issue for you?
> 
> Hi I'm using the following options for wikijs:
> 
> ```
>   - name: persistence.data.storageClass
>     value: "nfs-client"
>   - name: persistence.data.enabled
>     value: "true"
>   - name: persistence.config.enabled
>     value: "true"
>   - name: persistence.config.storageClass
>     value: "nfs-client"
> ```

These values look really strange to me, I would expect them to be something like:

```yaml
persistence:
  data:
    enabled: true
    storageClass: nfs-client
  config:
    enabled: true
    storageClass: nfs-client
```

**Pull request closed without merging**
