### PR TITLE
[Gluetun] Add VPN Addon

### PR DESCRIPTION
**Pull request by Y0ngg4n**
**Description of the change**

Add [gluetun](https://github.com/qdm12/gluetun) sidecar VPN Addon that provides multiple VPN Providers like windscribe, mulvad, cyberghost, nordvpn ...

**Benefits**

Easy connection to VPN Providers without downloading Certificates

**Possible drawbacks**

Untested. Don´t know if it works

**Additional information**

I have added it as good as i can. But i am sorry if i have done it wrong.

**Checklist** 
[] Code Review by someone knowing the code base
[] Testing
[] Add environment placeholder variables

### CODE REVIEW

**Comment by ThalusA** [comment]
Would love to see this PR released

**Comment by Y0ngg4n** [comment]
Same. Don´t know what it takes to merge this.

**Comment by onedr0p** [comment]
We are aware of this PR and want to add it, please be patient :)

**Comment by bjw-s** [comment]
> Same. Don´t know what it takes to merge this.

> > Untested. Don´t know if it works

This is the main thing that has been holding us back from merging tbh. But as @onedr0p said, we are aware of the PR and trying to see if we can get it in somehow.

**Comment by bjw-s** [comment]
I've been doing some local testing with the gluetun VPN container, and have been able to make it work. However, it doesn't support all of the current vpn add-on features, so we'll need to look at what needs to change for that.

I'll probably create a new branch/PR for that, but I'll definitely make sure to credit @Y0ngg4n for the PR that kicked it all off :)

**Comment by bjw-s** [comment]
It has been added in the `development` branch. It will be released with version 4.5.0 of the common library.

**Pull request closed without merging**
